name: Build and Push to Harbor

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Revision Number
        id: revision
        run: echo "revision=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Log in to Harbor
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          JFROG_REPO_URL: ${{ secrets.JFROG_REPO_URL }}
        run: |
          echo ${JFROG_USERNAME} ${JFROG_URL}
          docker build --build-arg JFROG_USERNAME=${JFROG_USERNAME} \
                       --build-arg JFROG_PASSWORD=${JFROG_PASSWORD} \
                       --build-arg JFROG_REPO_URL=${JFROG_REPO_URL} \
                       -t sanjaypramod/python-app:${{ env.revision }} .

      - name: Push Docker image to dockerhub
        run: docker push sanjaypramod/python-app:${{ env.revision }}
